"""add weight and category to players

Revision ID: 00b34843fe63
Revises: 2a6b7718a2a6
Create Date: 2026-08-13 16:27:02.650640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00b34843fe63'
down_revision: Union[str, Sequence[str], None] = '2a6b7718a2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'match_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('matches', 'service_order',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.JSON(),
               nullable=False)
    op.drop_column('officials', 'gender')
    op.drop_column('officials', 'email')
    op.drop_column('officials', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officials', sa.Column('date_of_birth', sa.DATE(), nullable=True))
    op.add_column('officials', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('officials', sa.Column('gender', mysql.VARCHAR(length=20), nullable=True))
    op.alter_column('matches', 'service_order',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('matches', 'match_type',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
