"""initial tables

Revision ID: 158e782f7c3c
Revises: 
Create Date: 2026-08-08 15:39:01.695211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158e782f7c3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(length=150), nullable=False),
    sa.Column('official_code', sa.String(length=50), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_code')
    )
    op.create_index(op.f('ix_officials_id'), 'officials', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=150), nullable=False),
    sa.Column('player_code', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_code')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('tbl_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_tbl_role_role_id'), 'tbl_role', ['role_id'], unique=False)
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tournament_code', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_code')
    )
    op.create_index(op.f('ix_tournament_id'), 'tournament', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_code', sa.String(length=50), nullable=True),
    sa.Column('match_no', sa.String(length=50), nullable=True),
    sa.Column('court_no', sa.String(length=50), nullable=True),
    sa.Column('round_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('player1_name', sa.String(length=150), nullable=False),
    sa.Column('player2_name', sa.String(length=150), nullable=False),
    sa.Column('umpire_id', sa.Integer(), nullable=True),
    sa.Column('match_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_server', sa.String(length=10), nullable=False),
    sa.Column('server', sa.String(length=10), nullable=False),
    sa.Column('player1_points', sa.Integer(), nullable=False),
    sa.Column('player2_points', sa.Integer(), nullable=False),
    sa.Column('is_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('tiebreak_player1_points', sa.Integer(), nullable=False),
    sa.Column('tiebreak_player2_points', sa.Integer(), nullable=False),
    sa.Column('player1_games', sa.Integer(), nullable=False),
    sa.Column('player2_games', sa.Integer(), nullable=False),
    sa.Column('player1_sets', sa.Integer(), nullable=False),
    sa.Column('player2_sets', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_code'], ['tournament.tournament_code'], ),
    sa.ForeignKeyConstraint(['umpire_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_role.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('match_point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=False),
    sa.Column('server', sa.String(length=10), nullable=False),
    sa.Column('point_type', sa.String(length=20), nullable=False),
    sa.Column('player1_score_after', sa.String(length=10), nullable=True),
    sa.Column('player2_score_after', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_point_logs_id'), 'match_point_logs', ['id'], unique=False)
    op.create_table('match_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('player1_games', sa.Integer(), nullable=False),
    sa.Column('player2_games', sa.Integer(), nullable=False),
    sa.Column('was_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('tiebreak_player1_points', sa.Integer(), nullable=True),
    sa.Column('tiebreak_player2_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_sets_id'), 'match_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_sets_id'), table_name='match_sets')
    op.drop_table('match_sets')
    op.drop_index(op.f('ix_match_point_logs_id'), table_name='match_point_logs')
    op.drop_table('match_point_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_tournament_id'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_index(op.f('ix_tbl_role_role_id'), table_name='tbl_role')
    op.drop_table('tbl_role')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_officials_id'), table_name='officials')
    op.drop_table('officials')
    # ### end Alembic commands ###
