"""add official email gender dob

Revision ID: 814604f7a16b
Revises: 00b34843fe63
Create Date: 2026-08-13 16:42:21.010370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '814604f7a16b'
down_revision: Union[str, Sequence[str], None] = '00b34843fe63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officials', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('officials', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('officials', sa.Column('gender', sa.String(length=20), nullable=True))
    op.alter_column('officials', 'role_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('officials', 'role_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('officials', 'gender')
    op.drop_column('officials', 'date_of_birth')
    op.drop_column('officials', 'email')
    # ### end Alembic commands ###
