"""add match metadata and officials

Revision ID: e8e5658b0bdd
Revises: 814604f7a16b
Create Date: 2026-08-13 22:27:57.150453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e5658b0bdd'
down_revision: Union[str, Sequence[str], None] = '814604f7a16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_date', sa.Date(), nullable=True))
    op.add_column('matches', sa.Column('match_time', sa.Time(), nullable=True))
    op.add_column('matches', sa.Column('match_category', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('age_category', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('digital_scorer_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('referee_1_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('referee_2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'officials', ['referee_1_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'officials', ['referee_2_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'officials', ['digital_scorer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'referee_2_id')
    op.drop_column('matches', 'referee_1_id')
    op.drop_column('matches', 'digital_scorer_id')
    op.drop_column('matches', 'age_category')
    op.drop_column('matches', 'match_category')
    op.drop_column('matches', 'match_time')
    op.drop_column('matches', 'match_date')
    # ### end Alembic commands ###
